name: Publish Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:     
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with: 
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: dorison/seogoogle:latest
          labels: ${{ steps.meta.outputs.labels }}
      - name: Self sast-scan
        uses: ShiftLeftSecurity/scan-action@master
        with:
          output: reports
          type: "php"
      - name: Upload scan reports
        uses: actions/upload-artifact@v1.0.0
        with:
          name: shiftleft-scan-reports
          path: reports
      - name: Test
        uses: stackhawk/hawkscan-action@v2.0.0
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          dryRun: true
